import { useDispatch, useSelector } from 'react-redux';
import {
	selectCategories,
	selectCategoryMap,
} from '../../store/category/category.selector';
import { ChangeEvent, useEffect, useState } from 'react';
import { fetchCategoriesStart } from '../../store/category/category.slice';
import TextInput from '../../components/text-input/text-input.component';
import Form from '../../components/form/form.component';
import WithHomeButton from '../../components/with-home-button/with-home-button.component';
import FloatInput from '../../components/float-input/float-input.component';
import { DimensionsContainer } from './add-product.styles';
import TextArea from '../../components/text-area/text-area.component';
import FileInput from '../../components/file-input/file-input.component';
import RadioChoice from '../../components/radio-choice/radio-choice.component';
import WithLabel from '../../components/with-label/with-label.component';
import { ProductRequestObject } from '../../store/product/product.types';
import { addProductStart } from '../../store/product/product.slice';
import SelectOption from '../../components/select-option/select-option.component';
import { selectProductIsLoading } from '../../store/product/product.selector';
import Spinner from '../../components/spinner/spinner.component';

const AddProduct = () => {
	const INITIAL_PRODUCT_STATE: ProductRequestObject = {
		code: '',
		name: '',
		weight: null,
		dimensions: {
			length: null,
			width: null,
			height: null,
		},
		categories: [],
		images: [],
		description: null,
		unitPreference: 'KG',
	};

	// MARK: State
	const [modifyCodeEnabled, setModifyCodeEnabled] = useState(false);

	const [weight, setWeight] = useState({
		value: 0,
		unit: 'KG',
	});

	const [product, setProduct] = useState(INITIAL_PRODUCT_STATE);

	const dispatch = useDispatch();

	// MARK: Selectors
	const categories = useSelector(selectCategories);
	const categoriesMap = useSelector(selectCategoryMap);
	const isProductLoading = useSelector(selectProductIsLoading);

	// MARK: Effects
	useEffect(() => {
		dispatch(fetchCategoriesStart());
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	useEffect(() => {
		setProduct((prevProduct) => ({
			...prevProduct,
			weight: weight.value * (weight.unit === 'KG' ? 1000 : 1),
		}));
	}, [weight]);

	useEffect(() => {
		if (!modifyCodeEnabled) {
			setProduct((prevProduct) => ({
				...prevProduct,
				code: autoGeneratedProductCode(),
			}));
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [product.categories, product.name, product.weight, modifyCodeEnabled]);

	// MARK: Event Handlers
	const handleChange = (
		event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
	) => {
		const { name, value } = event.target;
		setProduct((prevProduct) => ({
			...prevProduct,
			[name]: value,
		}));
	};

	const handleCategoryChange = (event: ChangeEvent<HTMLSelectElement>) => {
		const selectedOptions = Array.from(
			event.target.selectedOptions,
			(option) => option.value
		);
		setProduct((prevProduct) => ({
			...prevProduct,
			categories: selectedOptions.map((id) => ({ id })),
		}));
	};

	const handleDimensionsChange = (event: ChangeEvent<HTMLInputElement>) => {
		const { name, value } = event.target;
		let parsedValue: number | null = parseFloat(value);
		if (isNaN(parsedValue) || parsedValue <= 0) {
			parsedValue = null;
		}

		setProduct((prevProduct) => ({
			...prevProduct,
			dimensions: { ...prevProduct.dimensions, [name]: parsedValue },
		}));
	};

	const handleModifyCodeChange = () => {
		setModifyCodeEnabled((prev) => !prev);
	};

	const handleWeightChange = (event: ChangeEvent<HTMLInputElement>) => {
		const { name, value } = event.target;
		setWeight({ ...weight, [name]: value });
	};

	const handleFileChange = (files: File[]) => {
		setProduct({ ...product, images: files });
	};

	const handleSubmit = () => {
		dispatch(addProductStart(product));
	};

	// MARK: Utility Functions
	const autoGeneratedProductCode = () => {
		const parts = [];
		for (const category of product.categories) {
			const categoryName = categoriesMap.get(category.id);
			if (!categoryName) {
				continue;
			}
			parts.push(categoryName.slice(0, Math.min(3, categoryName.length)));
		}
		if (product.name.length > 0) {
			parts.push(
				product.name
					.split(' ')
					.map((word) => word.slice(0, Math.min(2, word.length)))
					.join('')
			);
		}
		if (product.weight && product.weight > 0) {
			parts.push(product.weight.toString());
		}
		return parts.join('_').toUpperCase();
	};

	// MARK: Render
	if (isProductLoading) {
		return <Spinner />;
	}

	return (
		<WithHomeButton>
			<Form title='Add Product' buttonText='Add' onSubmit={handleSubmit}>
				<TextInput
					label='Code'
					name='code'
					placeholder='code'
					disabled={!modifyCodeEnabled}
					onChange={handleChange}
					value={product.code}
				/>
				<div>
					<input
						type='checkbox'
						onChange={handleModifyCodeChange}
						id='modify-code'
					/>
					<label htmlFor='modify-code'>Modify code</label>
				</div>
				<TextInput
					label='Name'
					name='name'
					placeholder='name'
					onChange={handleChange}
					value={product.name}
				/>
				<RadioChoice
					choices={['KG', 'G']}
					label='Weight Unit'
					name='unit'
					onChoiceChange={handleWeightChange}
					selectedChoice={weight.unit}
					preChoiceElement={
						<FloatInput
							placeholder='Weight'
							name='value'
							onChange={handleWeightChange}
						/>
					}
				/>
				<RadioChoice
					label='Unit Preference'
					choices={['KG', 'PCS', 'BOXES']}
					selectedChoice={product.unitPreference}
					onChoiceChange={handleChange}
					name='unitPreference'
				/>
				<WithLabel
					label='Dimensions'
					element={
						<DimensionsContainer>
							<FloatInput
								placeholder='Length'
								name='length'
								onChange={handleDimensionsChange}
							/>
							&times;
							<FloatInput
								placeholder='Width'
								name='width'
								onChange={handleDimensionsChange}
							/>
							&times;
							<FloatInput
								placeholder='Height'
								name='height'
								onChange={handleDimensionsChange}
							/>
						</DimensionsContainer>
					}
				/>
				<WithLabel
					label='Category'
					element={
						<SelectOption
							options={categories}
							values={(category) => category.id}
							display={(category) => category.name}
							name='categories'
							onChange={handleCategoryChange}
							multiple
						/>
					}
				/>
				<FileInput
					label='Images'
					name='images'
					onFileChange={handleFileChange}
				/>
				<TextArea
					label='Description'
					name='description'
					onChange={handleChange}
				/>
			</Form>
		</WithHomeButton>
	);
};

export default AddProduct;
